config/routes.rb
Rails.application.routes.draw do

  get 'attempts/new'

  root   'static_pages#home'

  get    'help'    => 'static_pages#help'
  
  get    'about'   => 'static_pages#about'
  
  get    'contact' => 'static_pages#contact'
  
  get    'form'    => 'static_pages#form_test'
  
  get    'signup'  => 'users#new'
  
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  delete 'logout'  => 'session#destroy'
  
  resources :users
  
  get 'jokes/new' => 'jokes#new'
  post 'jokes/new' => 'jokes#create'
  
  get 'jokes/index' => 'jokes#index'
  
  
  get 'jokes/:id' => 'jokes#show'
  
  get 'jokes/:id/delete' => 'jokes#killpage'
  post 'jokes/:id/delete' => 'jokes#destroy'
  
  
  get 'questions/:id' => 'questions#show'
  post 'questions/:id' => 'session#answer_question_2'
  
  get 'newquiz' => 'attempts#new'
  post 'newquiz' => 'attempts#create'
  
  
  get 'quizpage' => 'static_pages#quiz_page'
  post 'quizpage' => 'session#and_one'
  
  get 'quizpage2' => 'static_pages#quiz_page2'
  post 'quizpage2' => 'session#and_two'
  
  get 'quizpage3' => 'static_pages#quiz_page3'
  post 'quizpage3' => 'session#and_three'
  
  get 'quizpage4' => 'static_pages#quiz_page4'
  post 'quizpage4' => 'session#answer_question'
  
  
    

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/choice.rb
class Choice < ActiveRecord::Base
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: {maximum: 255 }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                   BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def new
  end
  
  def create
    params[:attempt][:grade] = 0
    redirect_to quizpage_url
  end
  
  def destroy
  end
  
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  
  def show
    @joke = Joke.find(params[:id])
  end
  
  
  def new
    @joke = Joke.new
  end
  
  def create
    @joke = Joke.new(prompt: params[:prompt], punchline: params[:punchline], picture: params[:picture])
    if @joke.save
      redirect_to root_url
    else
      render "new"
    end
  end
  
  def index
  end
  
  def killpage
    @joke = Joke.find(params[:id])
  end
  
  def destroy
    Joke.find(params[:id]).destroy
    redirect_to '/jokes/index'
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end
  
  
###  @user = User.find(params[:id])
##    @microposts = @user.microposts.paginate(page: params[:paage])

  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render "new"
    end
  end
  
  def and_one
    session[:color] = params[:session][:color]
    redirect_to root_url
  end
  
  def and_two
    session[:color] = params[:color]
    redirect_to root_url
  end
  
  def and_three
    session[:color] = params[:color]
    redirect_to root_url
  end
  
  def answer_question
    answer = params[:color]
    if answer == 'correct'
      session[:answer] = 'correct'
      session[:quiz_grade] += 1
    else
      session[:answer] = 'wrong'
    end
    session[:quesiton] += 1
    redirect_to 
  end
  
  def answer_question_2
    answer = params[:president]
    if answer == 'true'
      session[:answer] = 'correct'
      session[:quiz_grade] += 1
    else
      session[:answer] = 'wrong'
    end
    session[:question] += 1
    if session[:question] <= Question.count
      redirect_to "/questions/" + String(session[:question])
    else
      redirect_to root_url
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:paage])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # handle a successful update
    else
      render 'edit'
    end
  end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  
  def log_in(user)
    session[:user_id] = user.id
    session[:quiz_grade] = 0
    session[:color] = 'red'
    session[:question] = 1
  end
  
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href = "http://railstutorial.org"><em>Ruby on Rails Tutorial</em></a> is a
  <a href = "http://www.railstutorial.org/book">book</a> and
  <a href = "http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href = "http://rubyonrails.org">Ruby on Rails</a>.
  <br>
  This is the smaple application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample ap at the
  <a href = "http://www.railstutorial.org/#contact">contact page</a>
</p>

app/views/static_pages/form_test.html.erb
<p>Hello its me</p>

<%= form_tag do %>
  <%= radio_button_tag(:fandom, "fan") %>
  <%= label_tag(:pats_fan, "I am a Patriots fan") %>
  <%= radio_button_tag(:fandom, "suck") %>
  <%= label_tag(:such, "I suck") %>
  <%= submit_tag("Answer") %>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the 
  <a href = "http://www.railstutorial.org/#help">Rails Tutorial Help section</a>.
  To get help in this sample app, see the 
  <a href = "http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial Book</em></a>.
</p>

app/views/static_pages/home.html.erb
<div class = "center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
  This is the home page for the <a href = "http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/quiz_page.html.erb
<p>i'm in california dreaming about who we used to be</p>
<p><%= session[:user_id] %></p>
<p><%= session[:quiz_grade] %></p>
<p><%= session[:color] %></p>

<%= form_for(:session, url: quizpage_path) do |f| %>
Form content here.
<%= f.label :color %>
<%= f.text_field :color %>
<%= f.submit "change color", class: "btn" %>
<% end %>

app/views/static_pages/quiz_page2.html.erb
<p>i'm in california dreaming about who we used to be</p>
<p><%= session[:user_id] %></p>
<p><%= session[:quiz_grade] %></p>
<p><%= session[:color] %></p>

<%= form_tag do %>
<%= label_tag(:color, "color") %>
<%= text_field_tag(:color) %>
<%= submit_tag("change_color") %>
<% end %>

app/views/static_pages/quiz_page3.html.erb
<p>i'm in california dreaming about who we used to be</p>
<p><%= session[:user_id] %></p>
<p><%= session[:quiz_grade] %></p>
<p><%= session[:color] %></p>

<%= form_tag do %>
<%= radio_button_tag(:color, "red") %>
<%= label_tag(:color_red, "RED") %>
<%= radio_button_tag(:color, "white") %>
<%= label_tag(:color_white, "WHITE") %>
<%= radio_button_tag(:color, "blue")  %>
<%= label_tag(:color_blue, "BLUE") %>
<%= submit_tag("change_color") %>
<% end %>

app/views/static_pages/quiz_page4.html.erb
<p>i'm in california dreaming about who we used to be</p>
<p><%= session[:user_id] %></p>
<p><%= session[:quiz_grade] %></p>
<p><%= session[:color] %></p>
<p><%= session[:answer] %></p>

<p>Which is not a color in the American Flag?</p>
<%= form_tag do %>
<%= radio_button_tag(:color, "wrong1") %>
<%= label_tag(:color_wrong1, "RED") %>
<%= radio_button_tag(:color, "wrong2") %>
<%= label_tag(:color_wrong2, "WHITE") %>
<%= radio_button_tag(:color, "wrong3")  %>
<%= label_tag(:color_wrong3, "BLUE") %>
<%= radio_button_tag(:color, "correct") %>
<%= label_tag(:color_correct, "PURPLE") %>
<%= submit_tag("change_color") %>
<% end %>